export const TABLES = {
  analyticsDashboardSnapshots: 'in_analytics_dashboard_snapshots',
  auditLogEvents: 'in_audit_log_events',
  canonicalMeteringEvents: 'in_canonical_metering_events',
  cutoverRecords: 'in_cutover_records',
  earningsLedger: 'in_earnings_ledger',
  fnfApiKeyOwnership: 'in_fnf_api_key_ownership',
  fnfTokenCredentialOwnership: 'in_fnf_token_credential_ownership',
  idempotencyKeys: 'in_idempotency_keys',
  meteringProjectorStates: 'in_metering_projector_states',
  orgs: 'in_orgs',
  pilotAdmissionFreezes: 'in_pilot_admission_freezes',
  rateCardLineItems: 'in_rate_card_line_items',
  rateCardVersions: 'in_rate_card_versions',
  requestLog: 'in_request_log',
  rollbackRecords: 'in_rollback_records',
  sellerKeys: 'in_seller_keys',
  tokenCredentialProviderUsage: 'in_token_credential_provider_usage',
  tokenCredentials: 'in_token_credentials',
  tokenCredentialEvents: 'in_token_credential_events',
  usageLedger: 'in_usage_ledger',
  walletLedger: 'in_wallet_ledger',
  withdrawalRequests: 'in_withdrawal_requests',
  dailyAggregates: 'in_daily_aggregates',
  reconciliationRuns: 'in_reconciliation_runs',
  routingEvents: 'in_routing_events'
} as const;
